[package]
name = "sign-txs"
version = "0.1.2"
edition = "2024"
description = "Sign transactions with bitcoind in a container"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
